### ISSUE TITLE
Please fix your repo

### ISSUE THREAD

**Issue by topjohnwu** [Magisk-Modules-Repo/Galaxy-Note-8-Dual-Speaker-Mod-Magisk-Module#1]
@ITDante93 , you **must** have a `master` branch on the repo. Magisk Manager only monitors that branch. Currently, you only have `v4` and `1400` these two branches.

Please fix it ASAP, or your module will be removed!

**Comment by ITDante93** [comment]
@topjohnwu ,
I hope this finds you well,
I am still new to github, so I have no clue what to do...
Is there a guide I can follow...?

**Comment by topjohnwu** [comment]
You should be able to do so.
I have done it for you though
